version: '3.8'

services:
  summarize_api: 
    container_name: summarize_api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/app
    depends_on:
      - summarize_db
  summarize_db:
    image: postgres:16
    container_name: summarize_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
